# Generated by Django 5.0.6 on 2024-10-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_titel', models.CharField(max_length=50)),
                ('task_description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('task_assaign_date', models.DateField()),
            ],
        ),
    ]
