# Generated by Django 5.0.6 on 2024-10-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_categorymodel_task_category_relation'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='task_category',
            field=models.ManyToManyField(to='category.categorymodel'),
        ),
    ]
